name = "braid_distance"
version = "0.1.0"
defaultTargets = ["BraidDistance", "OMDistance"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "BraidDistance"

[[lean_lib]]
name = "OMDistance"
